import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

import { ProjectTopbar } from "@/components/project-banner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/project.png",
    apple: "/project.png",
  },
  openGraph: {
    images: ["/project.png"],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/project.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProjectTopbar />
        <div className="flex-1 pt-16 sm:pt-[4.25rem]">{children}</div>
        <Analytics />
      </body>
    </html>
  );
}
